<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
    public function up(): void {
        Schema::create('users', function(Blueprint $t){$t->id();$t->string('name');$t->string('email')->unique();$t->timestamp('email_verified_at')->nullable();$t->string('password');$t->rememberToken();$t->timestamps();});
        Schema::create('password_reset_tokens', function(Blueprint $t){$t->string('email')->primary();$t->string('token');$t->timestamp('created_at')->nullable();});
        Schema::create('sessions', function(Blueprint $t){$t->string('id')->primary();$t->foreignId('user_id')->nullable()->index();$t->string('ip_address',45)->nullable();$t->text('user_agent')->nullable();$t->longText('payload');$t->integer('last_activity')->index();});
        Schema::create('merchants', function(Blueprint $t){$t->id();$t->string('name');$t->string('slug')->unique();$t->string('email')->nullable();$t->string('phone')->nullable();$t->string('currency',3)->default('TZS');$t->string('timezone')->default('Africa/Dar_es_Salaam');$t->string('status')->default('ACTIVE');$t->timestamps();});
        Schema::create('merchant_users', function(Blueprint $t){$t->id();$t->foreignId('merchant_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->string('role')->default('AGENT');$t->boolean('is_active')->default(true);$t->timestamps();$t->unique(['merchant_id','user_id']);});
        Schema::create('whatsapp_accounts', function(Blueprint $t){$t->id();$t->foreignId('merchant_id')->constrained()->cascadeOnDelete();$t->string('waba_id');$t->string('phone_number_id')->unique();$t->string('display_phone_number')->nullable();$t->string('verified_name')->nullable();$t->text('access_token');$t->string('status')->default('ACTIVE');$t->timestamp('last_webhook_at')->nullable();$t->timestamps();});
        Schema::create('customers', function(Blueprint $t){$t->id();$t->foreignId('merchant_id')->constrained()->cascadeOnDelete();$t->string('wa_id')->nullable();$t->string('name')->nullable();$t->string('phone');$t->string('email')->nullable();$t->string('locale',10)->nullable();$t->boolean('marketing_opt_in')->default(false);$t->timestamp('last_inbound_at')->nullable();$t->timestamp('last_outbound_at')->nullable();$t->timestamps();$t->unique(['merchant_id','phone']);$t->unique(['merchant_id','wa_id']);});
        Schema::create('products', function(Blueprint $t){$t->id();$t->foreignId('merchant_id')->constrained()->cascadeOnDelete();$t->string('sku')->nullable();$t->string('name');$t->text('description')->nullable();$t->string('type')->default('PRODUCT');$t->decimal('price',18,2);$t->decimal('cost_price',18,2)->nullable();$t->integer('stock_quantity')->default(0);$t->boolean('track_stock')->default(true);$t->boolean('is_active')->default(true);$t->json('metadata')->nullable();$t->timestamps();$t->unique(['merchant_id','sku']);$t->index(['merchant_id','name']);});
        Schema::create('conversations', function(Blueprint $t){$t->id();$t->foreignId('merchant_id')->constrained()->cascadeOnDelete();$t->foreignId('customer_id')->constrained()->cascadeOnDelete();$t->foreignId('whatsapp_account_id')->constrained()->cascadeOnDelete();$t->string('status')->default('OPEN');$t->string('mode')->default('AI');$t->foreignId('assigned_user_id')->nullable()->constrained('users')->nullOnDelete();$t->timestamp('last_message_at')->nullable();$t->timestamps();$t->index(['merchant_id','status','last_message_at']);});
        Schema::create('messages', function(Blueprint $t){$t->id();$t->foreignId('merchant_id')->constrained()->cascadeOnDelete();$t->foreignId('conversation_id')->constrained()->cascadeOnDelete();$t->foreignId('customer_id')->constrained()->cascadeOnDelete();$t->foreignId('whatsapp_account_id')->constrained()->cascadeOnDelete();$t->string('wamid')->nullable()->unique();$t->string('direction');$t->string('type')->default('text');$t->string('status')->default('RECEIVED');$t->text('body')->nullable();$t->json('payload')->nullable();$t->string('error_code')->nullable();$t->text('error_message')->nullable();$t->timestamp('sent_at')->nullable();$t->timestamp('delivered_at')->nullable();$t->timestamp('read_at')->nullable();$t->timestamps();$t->index(['merchant_id','conversation_id','created_at']);});
        Schema::create('orders', function(Blueprint $t){$t->id();$t->foreignId('merchant_id')->constrained()->cascadeOnDelete();$t->foreignId('customer_id')->constrained()->cascadeOnDelete();$t->string('number')->unique();$t->string('status')->default('DRAFT');$t->string('payment_status')->default('UNPAID');$t->string('currency',3)->default('TZS');$t->decimal('subtotal',18,2)->default(0);$t->decimal('delivery_fee',18,2)->default(0);$t->decimal('discount',18,2)->default(0);$t->decimal('total',18,2)->default(0);$t->string('delivery_method')->nullable();$t->text('delivery_address')->nullable();$t->text('notes')->nullable();$t->timestamp('paid_at')->nullable();$t->timestamps();$t->index(['merchant_id','status','created_at']);});
        Schema::create('order_items', function(Blueprint $t){$t->id();$t->foreignId('order_id')->constrained()->cascadeOnDelete();$t->foreignId('product_id')->nullable()->constrained()->nullOnDelete();$t->string('name');$t->string('sku')->nullable();$t->integer('quantity');$t->decimal('unit_price',18,2);$t->decimal('total',18,2);$t->timestamps();});
        Schema::create('payments', function(Blueprint $t){$t->id();$t->foreignId('merchant_id')->constrained()->cascadeOnDelete();$t->foreignId('order_id')->constrained()->cascadeOnDelete();$t->string('provider');$t->string('provider_reference')->nullable();$t->string('status')->default('PENDING');$t->decimal('amount',18,2);$t->string('currency',3);$t->string('msisdn')->nullable();$t->json('raw_request')->nullable();$t->json('raw_response')->nullable();$t->timestamp('paid_at')->nullable();$t->timestamps();$t->unique(['provider','provider_reference']);});
        Schema::create('subscription_plans', function(Blueprint $t){$t->id();$t->string('name');$t->string('code')->unique();$t->decimal('price',18,2);$t->string('currency',3)->default('TZS');$t->integer('message_limit')->nullable();$t->integer('product_limit')->nullable();$t->integer('user_limit')->nullable();$t->json('features')->nullable();$t->boolean('is_active')->default(true);$t->timestamps();});
        Schema::create('subscriptions', function(Blueprint $t){$t->id();$t->foreignId('merchant_id')->constrained()->cascadeOnDelete();$t->foreignId('subscription_plan_id')->constrained()->cascadeOnDelete();$t->string('status')->default('ACTIVE');$t->timestamp('starts_at');$t->timestamp('ends_at')->nullable();$t->unsignedInteger('messages_used')->default(0);$t->timestamps();});
        Schema::create('webhook_events', function(Blueprint $t){$t->id();$t->string('provider');$t->string('event_key')->unique();$t->string('event_type')->nullable();$t->json('payload');$t->timestamp('processed_at')->nullable();$t->timestamps();});
    }
    public function down(): void {
        foreach(['webhook_events','subscriptions','subscription_plans','payments','order_items','orders','messages','conversations','products','customers','whatsapp_accounts','merchant_users','merchants','sessions','password_reset_tokens','users'] as $table) Schema::dropIfExists($table);
    }
};
